Retry WP-ENV setup
This is an attempt to fix the "Error: Error establishing a database connection"
issue since we can't override WP-ENV's Docker setup and add a `healthcheck`
(or can we? :)).

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -24,6 +24,19 @@ jobs:
       - run:
           name: Run E2E tests
           command: |
+            attempt=0
+            max_attempts=3
+            sleep_time=5
+            while [ $attempt -lt $max_attempts ]; do
+              npm run tests:e2e:setup && break
+              attempt=$(( attempt + 1 ))
+              echo "Retrying WP-ENV setup in $sleep_time seconds... (Attempt $attempt/$max_attempts)"
+              sleep $sleep_time
+            done
+            if [ $attempt -eq $max_attempts ]; then
+              echo "WP-ENV setup failed."
+              exit 1
+            fi
             npm run tests:e2e:setup
             npm run tests:e2e:parallel
       - store_artifacts:
